AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
